FROM python:3.13-alpine AS builder
RUN apk add --no-cache \
    gcc \
    g++ \
    musl-dev \
    libffi-dev \
    rust \
    cargo \
    openssl-dev
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry==2.1.1
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false
RUN poetry install --no-root --only main

FROM python:3.13-alpine as deps-image
RUN apk add --no-cache libffi
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin/uvicorn /usr/local/bin/uvicorn
