version: 2.1

parameters:
  docker-username:
    type: string
    default: ${DOCKER_USERNAME}
  docker-password:
    type: string
    default: ${DOCKER_PASSWORD}
  image-name:
    type: string
    default: "leonhrt/dev-images-hub"
  image-tag:
    type: string
    default: "${CIRCLE_SHA1:0:7}"

orbs:
  docker: circleci/docker@2.2.0

executors:
  amd64-executor:
    docker:
      - image: cimg/base:2023.03
    resource_class: medium
  arm64-executor:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

jobs:
  build-and-push-amd64:
    executor: amd64-executor
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: << pipeline.parameters.image-name >>
          tag: << pipeline.parameters.image-tag >>-amd64
          extra_build_args: --platform=linux/amd64
      - docker/push:
          image: << pipeline.parameters.image-name >>
          tag: << pipeline.parameters.image-tag >>-amd64

  build-and-push-arm64:
    executor: arm64-executor
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: << pipeline.parameters.image-name >>
          tag: << pipeline.parameters.image-tag >>-arm64
          extra_build_args: --platform=linux/arm64
      - docker/push:
          image: << pipeline.parameters.image-name >>
          tag: << pipeline.parameters.image-tag >>-arm64

  create-manifest-and-push:
    executor: amd64-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker CLI plugins for buildx
          command: |
            mkdir -p ~/.docker/cli-plugins
            curl -L -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64
            chmod +x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
      - run:
          name: Create and push multi-architecture manifest
          command: |
            # Check if credentials are available
            if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
              echo "Error: Docker Hub credentials not available. Please ensure DOCKER_USERNAME and DOCKER_PASSWORD are set in the CircleCI context."
              exit 1
            fi
            
            # Login to Docker Hub with explicit credentials
            docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
            
            # Create the manifest
            docker buildx imagetools create \
              --tag << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >> \
              --tag << pipeline.parameters.image-name >>:latest \
              << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>-amd64 \
              << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>-arm64
            
            # Verify the manifest
            docker buildx imagetools inspect << pipeline.parameters.image-name >>:<< pipeline.parameters.image-tag >>

workflows:
  version: 2
  build-multiarch-image:
    jobs:
      - build-and-push-amd64:
          context:
            - dockerhub-credentials
      - build-and-push-arm64:
          context:
            - dockerhub-credentials
      - create-manifest-and-push:
          requires:
            - build-and-push-amd64
            - build-and-push-arm64
          context:
            - dockerhub-credentials
          filters:
            branches:
              only: main
