name: Build and Push Base Image

env:
  DOCKERHUB_REPO: leonhrt/dev-images-hub
  IMAGE_AMD64: nutria-testagent-app-amd64
  IMAGE_ARM64: nutria-testagent-app-arm64
  MANIFEST: nutria-testagent-app

on:
  push:
    branches: 
      - main
    paths:
      - 'app/**'
      - 'Dockerfile.app'
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AMD64 app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.app
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_AMD64 }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_AMD64 }}-cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_AMD64 }}-cache,mode=max

  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ARM64 app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.app
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_ARM64 }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_ARM64 }}-cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_ARM64 }}-cache,mode=max
