name: Build and Push Images

env:
  DOCKERHUB_REPO: leonhrt/dev-images-hub
  # Variables para imágenes base
  BASE_IMAGE_AMD64: nutria-testagent-base-amd64
  BASE_IMAGE_ARM64: nutria-testagent-base-arm64
  BASE_MANIFEST: nutria-testagent-base
  # Variables para imágenes de aplicación
  APP_IMAGE_AMD64: nutria-testagent-app-amd64
  APP_IMAGE_ARM64: nutria-testagent-app-arm64
  APP_MANIFEST: nutria-testagent-app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'Dockerfile.app'
      - 'Dockerfile.base'
      - 'poetry.lock'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      base-changed: ${{ steps.changes.outputs.base-changed }}
      app-changed: ${{ steps.changes.outputs.app-changed }}
      should-build-app: ${{ steps.set-outputs.outputs.should-build-app }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            base-changed:
              - 'Dockerfile.base'
              - 'poetry.lock'
              - 'pyproject.toml'
            app-changed:
              - 'app/**'
              - 'Dockerfile.app'

      # Agregar un paso para determinar si debemos construir la app
      - name: Set additional outputs
        id: set-outputs
        run: |
          if [[ "${{ steps.changes.outputs.app-changed }}" == "true" || "${{ steps.changes.outputs.base-changed }}" == "true" ]]; then
            echo "should-build-app=true" >> $GITHUB_OUTPUT
          else
            echo "should-build-app=false" >> $GITHUB_OUTPUT
          fi

  # Base image build - solo se ejecuta si hay cambios en la base
  build-base-amd64:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.base-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AMD64 base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_AMD64 }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_AMD64 }}-cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_AMD64 }}-cache,mode=max

  build-base-arm64:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.base-changed == 'true' }}
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ARM64 base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_ARM64 }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_ARM64 }}-cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_ARM64 }}-cache,mode=max

  create-base-manifest:
    needs:
      - build-base-amd64
      - build-base-arm64
    if: ${{ needs.detect-changes.outputs.base-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Inspect source images
        run: |
          echo "Inspecting AMD64 image..."
          docker manifest inspect ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_AMD64 }}
          
          echo "Inspection ARM64 image..."
          docker manifest inspect ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_ARM64 }}
      - name: Create Multi-Architecture Manifest
        run: |
          docker buildx imagetools create \
            --tag ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_MANIFEST }} \
            ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_AMD64 }} \
            ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_IMAGE_ARM64 }}
      
      - name: Verify new manifest
        run: |
          echo "Verifying new manifest..."
          docker manifest inspect ${{ env.DOCKERHUB_REPO }}:${{ env.BASE_MANIFEST }}

  # Un job para determinar si podemos pasar a la fase de app
  start-app-phase:
    needs:
      - detect-changes
      - create-base-manifest
    # Este job se ejecutará cuando:
    # 1. No hay cambios en la base pero sí en la app (o base)
    # 2. Hay cambios en la base (y posiblemente también en la app) y ya se ha completado la fase de base
    if: |
      always() && 
      needs.detect-changes.outputs.should-build-app == 'true' && 
      (needs.detect-changes.outputs.base-changed != 'true' || needs.create-base-manifest.result == 'success')
    runs-on: ubuntu-latest
    outputs:
      proceed: 'true'  # Añadido para pasar el testigo a los siguientes jobs
    steps:
      - name: Prepare app phase
        run: echo "Preparando fase de construcción de app"

  # App image build - se ejecuta después de la fase base (si hay cambios en base) o directamente (si solo hay cambios en app)
  build-app-amd64:
    needs: start-app-phase
    if: ${{ needs.start-app-phase.outputs.proceed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AMD64 app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.app
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_AMD64 }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_AMD64 }}-cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_AMD64 }}-cache,mode=max

  build-app-arm64:
    needs: start-app-phase
    if: ${{ needs.start-app-phase.outputs.proceed == 'true' }}
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ARM64 app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.app
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_ARM64 }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_ARM64 }}-cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_ARM64 }}-cache,mode=max

  create-app-manifest:
    needs: 
      - build-app-amd64
      - build-app-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Inspect source images
        run: |
          echo "Inspecting AMD64 image..."
          docker manifest inspect ${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_AMD64 }}
          
          echo "Inspection ARM64 image..."
          docker manifest inspect ${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_ARM64 }}
          
      - name: Create Multi-Architecture Manifest
        run: |
          docker buildx imagetools create \
            --tag ${{ env.DOCKERHUB_REPO }}:${{ env.APP_MANIFEST }} \
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_AMD64 }} \
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_IMAGE_ARM64 }}
      
      - name: Verify new manifest
        run: |
          echo "Verifying new manifest..."
          docker manifest inspect ${{ env.DOCKERHUB_REPO }}:${{ env.APP_MANIFEST }}
