name: Create Multi-Architecture Manifest
on:
  workflow_dispatch:
    inputs:
      amd64_tag:
        description: 'AMD64 image tag (sin el prefijo leonhrt/dev-images-hub:)'
        required: true
        default: 'agent-test-amd64-c1da890df23b20fe6a75850e4655d6bf0d93c514'
      arm64_tag:
        description: 'ARM64 image tag (sin el prefijo leonhrt/dev-images-hub:)'
        required: true
        default: 'agent-test-arm64-c1da890df23b20fe6a75850e4655d6bf0d93c514'
      output_tag:
        description: 'Tag de salida para la imagen multi-arquitectura'
        required: true
        default: 'agent-test-k3s'

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Inspect source images
        run: |
          echo "Inspecting AMD64 image..."
          docker manifest inspect leonhrt/dev-images-hub:${{ github.event.inputs.amd64_tag }}
          
          echo "Inspection ARM64 image..."
          docker manifest inspect leonhrt/dev-images-hub:${{ github.event.inputs.arm64_tag }}
      
      - name: Create multi-architecture manifest
        run: |
          # Eliminamos cualquier manifiesto existente con el mismo nombre
          docker manifest rm leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }} || true
          
          # Creamos el manifiesto usando buildx imagetools (método moderno)
          docker buildx imagetools create \
            --tag leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }} \
            leonhrt/dev-images-hub:${{ github.event.inputs.amd64_tag }} \
            leonhrt/dev-images-hub:${{ github.event.inputs.arm64_tag }}
          
      
      - name: Fallback to classical manifest method
        if: failure()
        run: |
          echo "buildx imagetools failed, retry with docker manifest..."
          
          docker manifest create leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }} \
            leonhrt/dev-images-hub:${{ github.event.inputs.amd64_tag }} \
            leonhrt/dev-images-hub:${{ github.event.inputs.arm64_tag }}
          
          docker manifest annotate --arch amd64 leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }} \
            leonhrt/dev-images-hub:${{ github.event.inputs.amd64_tag }}
          docker manifest annotate --arch arm64 leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }} \
            leonhrt/dev-images-hub:${{ github.event.inputs.arm64_tag }}
          
          docker manifest push leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }}

      - name: Verify new manifest
        run: |
          echo "Verifying new manifest..."
          docker manifest inspect leonhrt/dev-images-hub:${{ github.event.inputs.output_tag }}
